language: ruby
sudo: false
cache: bundler
bundler_args: --without test --jobs 3 --retry 3
before_install:
  - "travis_retry gem update --system"
  - "travis_retry gem install bundler"

script:
  - bundle exec rspec spec/

rvm:
  - 2.4.3
  - 2.5.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

notifications:
  email: false
